fix: const require replacement breaking test suite (#9)
This addresses the error:

```
ReferenceError: _b79‍__esm_req__ is not defined
```

introduced by commit c6d40cb4ebe6a24463be9980628e5220460bceba, which
was mentioned in https://github.com/nktnet1/esm-sync/issues/5